<a href="https://colab.research.google.com/github/Salman-a-gamer/Python-Programs/blob/main/practising_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# import statistics
# import random
import numpy as np

In [12]:
# create an array
array1d = np.array([1,2,3,4,5])
array2d = np.array([[1,2,3], [4,5,6], [7,8,':']])
print(array2d)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' ':']]


In [ ]:
# get the dimension of the array.
print(array2d.ndim)
array1d

2


In [ ]:
# get the shape of the array.
print(array1d.shape)
array2d.shape

(5,)


(3, 3)

In [ ]:
# data type of an element
print(array1d.dtype)
print(array2d.dtype)

int64
<U21


In [ ]:
# get the size in bytes of an element
print(array1d.itemsize)
print(array2d.itemsize)


8
84


In [ ]:
# get the no. of elements in each array
print(array1d.size)
print(array2d.size)

5
9


In [ ]:
#get total size of array
print(array1d.nbytes)
array2d.nbytes

40


756

In [ ]:
# accessing elements...
# arrayname[row  ,  col ]
print(array1d[:]) # get entire elements
print(array2d[:, 2]) # get all rows, with column 1 -> getting a specific column

[1 2 3 4 5]
['3' '6' ':']


In [8]:
# initialize a new array
np.zeros((2,2), dtype = 'int16')

array([[0, 0],
       [0, 0]], dtype=int16)

In [10]:
np.ones((2,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [15]:
print(array1d)
np.full_like(array1d.shape, 44)

[1 2 3 4 5]


array([44])

In [20]:
# getting random arrays
print(np.random.rand(3,1))
print(np.random.randint(4,8, size = (2,2)))  # 8 is exclusize

[[0.0163345 ]
 [0.64930748]
 [0.05183472]]
[[7 7]
 [7 6]]


In [21]:
# yo i can create an identitty matrix
np.identity(3,dtype='int16')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [27]:
n = np.full((5,5), 1)
n[1:4, 1:4] = 0
n[2,2] = 9
print(n)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


89

In [35]:
b = [1,2,3]
a = [[[1,2] , [1,2]]]
a += b
print(a)
arr = np.arange(6)
arr

[[[1, 2], [1, 2]], 1, 2, 3]


array([0, 1, 2, 3, 4, 5])

In [3]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


do some aggregate functions... and move on to pandas